var searchData=
[
  ['target_20implementations_0',['Target implementations',['../group__gbsv__specialization.html',1,'(Global Namespace)'],['../group__gelqf__specialization.html',1,'(Global Namespace)'],['../group__geqrf__specialization.html',1,'(Global Namespace)'],['../group__gesv__impl.html',1,'(Global Namespace)'],['../group__group__blas2__specialization.html',1,'(Global Namespace)'],['../group__group__blas3__specialization.html',1,'(Global Namespace)'],['../group__heev__impl.html',1,'(Global Namespace)'],['../group__heev__specialization.html',1,'(Global Namespace)'],['../group__hegv__specialization.html',1,'(Global Namespace)'],['../group__hesv__specialization.html',1,'(Global Namespace)'],['../group__norm__specialization.html',1,'(Global Namespace)'],['../group__pbsv__specialization.html',1,'(Global Namespace)'],['../group__posv__specialization.html',1,'(Global Namespace)'],['../group__svd__specialization.html',1,'(Global Namespace)'],['../group__tr__specialization.html',1,'(Global Namespace)']]],
  ['tbsm_3a_20_20triangular_20solve_20band_20matrix_1',['tbsm:  Triangular solve band matrix',['../group__tbsm.html',1,'(Global Namespace)'],['../group__tbsm__specialization.html',1,'(Global Namespace)']]],
  ['tile_2',['Tile',['../group__gelqf__tile.html',1,'(Global Namespace)'],['../group__geqrf__tile.html',1,'(Global Namespace)'],['../group__gesv__tile.html',1,'(Global Namespace)'],['../group__group__blas2__tile.html',1,'(Global Namespace)'],['../group__group__blas3__tile.html',1,'(Global Namespace)'],['../group__hegv__tile.html',1,'(Global Namespace)'],['../group__norm__tile.html',1,'(Global Namespace)'],['../group__posv__tile.html',1,'(Global Namespace)'],['../group__tr__tile.html',1,'(Global Namespace)']]],
  ['triangular_3',['Triangular',['../group__group__tr.html',1,'']]],
  ['trmm_3a_20_20triangular_20matrix_20multiply_4',['trmm:  Triangular matrix multiply',['../group__trmm.html',1,'(Global Namespace)'],['../group__trmm__internal.html',1,'(Global Namespace)'],['../group__trmm__specialization.html',1,'(Global Namespace)'],['../group__trmm__tile.html',1,'(Global Namespace)']]],
  ['trsm_3a_20_20triangular_20solve_20matrix_5',['trsm:  Triangular solve matrix',['../group__trsm.html',1,'(Global Namespace)'],['../group__trsm__impl.html',1,'(Global Namespace)'],['../group__trsm__internal.html',1,'(Global Namespace)'],['../group__trsm__tile.html',1,'(Global Namespace)']]]
];
